# Generated by Django 4.1.4 on 2022-12-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_design', '0002_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.IntegerField(default=0)),
                ('tagname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='tagid',
            field=models.IntegerField(default=0),
        ),
    ]
