# Generated by Django 4.1.4 on 2022-12-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_design', '0003_tagtest_tag_tagid'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageid',
            field=models.IntegerField(default=0),
        ),
    ]
