# Generated by Django 4.1.4 on 2022-12-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("show_design", "0004_delete_tagtest_image_imageid"),
        ("show_design", "0004_image_imageid"),
    ]

    operations = []
