# Generated by Django 4.1.4 on 2022-12-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show_design", "0005_merge_20221228_0400"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imageid", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=1000)),
            ],
        ),
    ]
