# Generated by Django 4.1.4 on 2022-12-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show_design", "0006_imageurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageurl",
            name="tagid",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
