# Generated by Django 4.1.4 on 2023-01-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_design', '0007_imageurl_tagid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeMondel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageid', models.CharField(max_length=100)),
                ('themename', models.CharField(max_length=100)),
            ],
        ),
    ]
