# Generated by Django 4.1.4 on 2023-01-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_design', '0008_thememondel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThemeMondel',
            new_name='Theme',
        ),
    ]
