# Generated by Django 4.1.4 on 2023-01-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_design', '0009_rename_thememondel_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Desk',
        ),
        migrations.RenameField(
            model_name='desk',
            old_name='themename',
            new_name='sizename',
        ),
    ]
