# Generated by Django 4.1.5 on 2023-01-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_design', '0010_rename_theme_desk_rename_themename_desk_sizename'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageurl',
            name='imageurl',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
